= dRCM: ABC
:idprefix:
:idseparator: -
:toc: preamble

[.lead]
Familiarize yourself with terminology we use throughout guides about dR Community Matrix.

== Glossary

=== client

Application capable of interacting with <<homeserver>> and peers via Matrix protocol. Upon logging in to <<user>>'s account, it is acknowledged as a separate "device".

=== dR

Short for "https://devrant.com/[devRant]". By using this acronym in various titles, we imply no affiliation to devRant, while still referring to activities with inclusion of related community.

=== dRCM

dR Community Matrix, a <<space>> in Matrix <<federation>> where all users of <<dR>> that pass <<verification>> are welcome to have some chat with like-minded people. Title is derivative of one "dR Community Server", Discord guild that was created back in 2020.

=== event

Universal <<timeline>> entry that has certain timestamp, originating <<user>>, some other metadata, and optional content. Easily represented as JSON string.

=== federation

Network of interconnected <<homeserver,homeservers>> that keep <<event,events>> synchronized between each other and add to <<redundancy>>.

=== history

Piece of <<timeline>> readily available to the <<user>> since the point they were allowed from. ^<<history-visibility>>^

=== homeserver

Server instance that implements Matrix Specification and acts as a "home" for <<user,users>> that sign up at and depend on to keep <<event,events>> going. Homeserver may or may not be in <<federation>>, which is a focal point in discoverability of its users and <<room,rooms>> via other servers.

=== member

Representation of the <<user>> in context of some <<room>>. Member can have a display name and avatar different from originating <<user>> to act like an alias.

=== message

Type of <<event>> used for written-out communication. Its content can be erased by <<redaction>>.

=== MSC

Matrix Spec Change, which can be thought of as RFC, but for Matrix Specification. Any MSC is usually referred to as a https://spec.matrix.org/proposals/[proposal] that foregoes submission process with participation of https://matrix.org/foundation/[Spec Core Team (SCT)]. Proposals are openly governed through https://github.com/matrix-org/matrix-spec-proposals[`matrix-spec-proposals`] repository.

=== MXID

Unique Matrix user ID, consisting of username and <<homeserver>> host name. Few examples: `@username:homeserver.tld`, `@drcm:envs.net`. It is immutable, so usernames are to be chosen wisely upon registration.

=== online status

Latest known awake state of <<user>> determined by <<homeserver>> based on ping it received from any connected <<client>>.

=== presence

Means of determining current activity of a <<user>> from ephemeral events and states: <<read-receipt, read receipts>>, <<typing-notification, typing notifications>>, and <<online-status>>.

=== read receipt

Marker sent by <<client>> to indicate that yet another <<event>> was marked as read by <<user>>. It lets interested users better understand their involvement with a discussion, or <<room>> in general. Client also can send private read receipts for maintaining reduced <<presence>>. ^<<msc2285>>^

=== redaction

Type of <<event>> used to briefly refer to another <<event>> whose content is being erased and by which <<user>>.

=== redundancy

A term used to describe copying the same set of data across multiple instances to mitigate any probable outage of just a few.

=== room

Conversation channel with separate <<timeline>>, <<member>> list, set of permissions, and miscellaneous <<state>>.

=== space

Kind of a <<room>> that serves as layer for aggregating and discovering other <<room,rooms>> (including <<space,subspaces>>). One can think of them as "guilds" in Discord, although it would be a rough comparison.

=== state

Data that is supposed to be promptly fetched from <<homeserver>> without reproducing any set of <<event,events>>. In turn, however, sending an event is required for introducing any modification.

=== timeline

Reproducible sequence of <<event,events>> that comprise entire conversation in the <<room>> along with traces of <<state>> mutations and <<redaction,redactions>>.

=== typing notification

Marker sent by <<client>> to indicate that <<user>> is typing out a text for <<message>> in certain <<room>>. It lets participating <<user,users>> better choose the timing of their correspondence, and be aware if someone's on their way to respond.

=== user

Agent on behalf of which human or automated program interacts with <<homeserver>> it was created on. Managed under account with appointed <<MXID>>.

=== verification

Procedure for ensuring the adequacy of potential <<member>>, as they own account with enough score on <<dR>>. Score requirement comes from a place of automatized verification, but it also may be performed manually by moderators.

[bibliography]
== References

- [[[history-visibility]]] "Room History Visibility". <https://github.com/matrix-org/matrix-spec/blob/main/content/client-server-api/modules/historyvisibility.md>.
- [[[msc2285]]] "Spec MSC2285: Private read receipts". <https://github.com/matrix-org/matrix-spec/pull/1216>.
